### ISSUE TITLE
Further optimize camera poses during radiance field reconstruction

### ISSUE THREAD

**Issue by JiamingSuen** [hwanhuh/Radiance-Fields-from-VGGSfM-Mast3r#2]
Thanks for this amazing repo! I'm curious if it will produce better radiance field reconstruction if we further optimize the initial camera poses from mast3r or vggsfm. [splatfacto in nerfstudio](https://github.com/nerfstudio-project/nerfstudio/pull/3116) should have already implemented this feature.

**Comment by hwanhuh** [comment]
In my opinion, VGG-SfM’s pose is already quite accurate.

For MAST3R, it’s not suitable for learning radiance fields without additional optimization of camera parameters, as noted in the repo. However, it seems to be a good initial point for methods similar to BARF. Below is a quick experiment with the penguins-MAST3R poses:

https://github.com/user-attachments/assets/d5b7ba98-7d51-4b20-a81e-6f5e4c00a79d

On the other hand, I haven’t observed any significant quality improvement with VGG-SfM’s pose.

**Comment by JiamingSuen** [comment]
Thanks for your rapid response! I'm glad that the mast3r poses can be further optimized in splatfacto. This should help in registering images that COLMAP fails to process. From my experience, I've noticed that VGGSfM has a lower registration rate compared to mast3r, although VGGSfM poses tend to be more accurate. Have you observed similar results?

**Comment by hwanhuh** [comment]
+For the guitar-MAST3R in SplatFacto:

https://github.com/user-attachments/assets/d279c7c1-34dc-4e4d-b28b-e2872de71d17

I’ve observed a similar, but the difference seems minor when dealing with a limited number of images. 
Since VGGSfM can handle slightly more images within the same VRAM, it appears to be a trade-off between the two methods.

**Comment by jytime** [comment]
Hi @JiamingSuen ,

Could you please share the cases where VGGSfM has a lower registration rate compared to mast3r? It would be much appreciated if you could provide the images or the download links, and I can investigate further. I am happy to check why this happens and improve the method. 

Usually this can be solved by just slightly increasing the value of ```query_frame_num```. In our latest version, increasing ```query_frame_num``` only results in a longer processing time but does not require additional GPU memory.

**Comment by JiamingSuen** [comment]
> Hi @JiamingSuen ,
> 
> Could you please share the cases where VGGSfM has a lower registration rate compared to mast3r? It would be much appreciated if you could provide the images or the download links, and I can investigate further. I am happy to check why this happens and improve the method.
> 
> Usually this can be solved by just slightly increasing the value of `query_frame_num`. In our latest version, increasing `query_frame_num` only results in a longer processing time but does not require additional GPU memory.

Hi Jianyuan, I've only tested a few extreme cases with minimal view overlapping. [Here](https://drive.google.com/file/d/1-RRS6JjRSXgU2OBS6hu0ASSBMMOKKVz5/view?usp=sharing) is one of the image sets I used. I didn't adjust the `query_frame_num` value though. 

must3r registered all eight images:

https://github.com/user-attachments/assets/bffb6c87-0440-4aa5-971d-3302fe61fa4b

while vggsfm produced some degraded results:

https://github.com/user-attachments/assets/a110f46d-b59c-4e1a-95c5-5eac0c85334f

**Comment by jytime** [comment]
Hi Jiaming,

Thanks for sharing it. 

The default hyper-parameters were not designed for extreme cases like this. For scenarios with sparse views and minimal overlap, the simplest solution is to set query_frame_num to the total number of your images, and use a ```max_query_pts``` like 4096 or more. This ensures all frames are registered. Since we have only sparse views (e.g., in this case, 8), the inference remains very fast.

For instance, for your scene, I ran the following command with query_frame_num=8. It took only around 20 seconds on my machine:
```
python demo.py SCENE_DIR=examples/compare_sfm/ visualize=True query_frame_num=8 max_query_pts=4096 query_method="aliked" 
```

It gives me a reconstruction like:

https://github.com/user-attachments/assets/a91ca4a4-7987-46f8-b4f7-ee172afa8de2

Furthermore, if you are aware that the images were captured by the same camera without a clear focal length change (e.g., the case you provided here), it is always helpful to set ```shared_camera``` as True. (please use our latest commit since there was a small bug with shared_camera before)

I will update an instruction in our readme page.
