### ISSUE TITLE
Any quantitative comparison about mast3r_with_pose_opt. and VGGSfM?

### ISSUE THREAD

**Issue by Reed-yang** [hwanhuh/Radiance-Fields-from-VGGSfM-Mast3r#4]
As title describes.

for your amazing repo, thx in advance

**Comment by hwanhuh** [comment]
I'm sorry for not getting back to you sooner.

First, I would like to clarify that during this personal project, I did not conduct experiments on datasets with ground truth camera poses (e.g., Blender synthetic datasets). 
The primary objective of this project was to evaluate how effectively deep-based SfM methods, which are faster and more robust than conventional SfM, can be applied to neural rendering-based reconstruction.

Instead, as briefly mentioned in the project description, I conducted indirect quantitative evaluations. 
The custom dataset I tested here consisted of over 100 images, for which I had COLMAP results available. This repository uses subsets of that dataset. 
I measured the angular distance and L2 distance errors between the [R|t] predicted by VGGSfM and Mast3R and the COLMAP poses for each subset. 
As noted briefly toward the end of the project description, VGGSfM achieved errors below 0.01, whereas Mast3R produced errors exceeding 0.1. 
While the amount of data used for these experiments may not be sufficient, I believe the general trend would hold for typical cases.

If a more formal comparison of camera pose optimization is required, it would likely involve using datasets with GT poses and adding random noise, as reported in works such as BARF. 
However, since this is a personal project that is not related to a research paper, such evaluations were not conducted.

Thank you for your interest in the project!
